name: Build and Deploy
on: 
  workflow_dispatch
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Push to ACR
        run: |
          az acr login -n sslablabacrgcasanova
          docker tag myapp:latest sslablabacrgcasanova.azurecr.io/myapp:latest
          docker push sslablabacrgcasanova.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g ss-lab-rg \
          -n sslab-webapp \
          --container-image-name sslablabacrgcasanova.azurecr.io/myapp:latest \
          --container-registry-url https://sslablabacrgcasanova.azurecr.io \
          --container-registry-user <USERNAME> \
          --container-registry-password <PASSWORD>
